### ISSUE TITLE
Disable dark theme

### ISSUE THREAD

**Issue by JesJehle** [hydrocode-de/integra-frontend#112]
@mmaelicke I would suggest removing the theme selection for now and just sticking with. the light theme. It's just more work to design everything for both. 
Since currently the theme is used based on the browser settings, things could look bad on dark theme. Removing it would solve the problem. Nobody cares.

**Comment by mmaelicke** [comment]
Yeah, I see the point with the new PRs. Before, everything looked really fine in both themes. Maybe if we utilize the variants distributed with MUI more, as they usually have both covered.

Hmm, I always only use dark themes all the time everywhere, because white screens suck. But I get the point, I will drop a PR fixing this soon.

**Comment by mmaelicke** [comment]
This was done along the way
