### ISSUE TITLE
Implement 'blüte' result card

### ISSUE THREAD

**Issue by mmaelicke** [hydrocode-de/integra-frontend#132]
**Blüte**: 
![image](https://github.com/hydrocode-de/integra-frontend/assets/23353378/1bb7e9f5-c65c-468a-9557-493c400a4210)
* **tab bar container** - horizontal barchart Blühzeitpunkt 
* **tab bar container** - stacked area chart Blühangebot (Nektar or Blüten or pollen (gespräch mit felix))
* **map** - tree icons (having blossom) supported by additional small icon (blossom - bool)

_Originally posted by @JesJehle in https://github.com/hydrocode-de/integra-frontend/issues/120#issuecomment-2098228833_

**Comment by karpaddel** [comment]
We currently discussed the blossom icon in the map. We think, a flower icon next to the trees would not look good.
We have two new ideas. But we are not sure, which we prefer:

1. Similar to the Biomasse-Tab a circle is shown around the tree position for the trees in blossom. The colour would be some sort of pink or rose (similar to the Blüten-Tab itself).
2. Instead of a simple circle around the tree position there is a flower icon. For example, we like the one from the Material icon collection called "FilterVintage", also in pink/rose.

As we are not sure, how it would look like on the map, we propose the following course of action:
Could you @mmaelicke implement the (for you) easier of the two options, so that we could see how it would look?
Then we can decide to keep it or try the more complicated option.

**Comment by mmaelicke** [comment]
OK, just that I get this right:

1. pink circle around the tree, depending on the amount of blossoms, but the tree icon is kept
2. completely *replace* the tree icon with a blossom icon? 

Then, the first option is the by magnitudes easier to implement, I guess. So, if I got you right, I would go for that one first.

Do blossoms follow a season, like (mar - may), or the flowering data? What should be shown if the flowering is not 'active'? Or should the blossoms data be treated like annual averages and not respond to the mont-slider at all?

**Comment by karpaddel** [comment]
No, not completely:

1. pink circle around the tree position (similar to the biomass circle) but with a fixed size, not depending on amount of blossoms. Tree icon is kept.
2. Same thing as above -> tree icon is also kept. But circle replaced by a flower icon.

The blossoms follow the flowering data from the "Reduzierte_Arten_allData..." table.
