### ISSUE TITLE
Implement actual tree lines (with a width and therefore also an area)

### ISSUE THREAD

**Issue by mmaelicke** [hydrocode-de/integra-frontend#140]
Currently, the tree-lines already have a length of 5m, which cannot be changed. Therefore #131 is technically possible. But a few further steps are necessary, to provide a UX:

- [x] visualize the tree line on the map
- [ ] ~implement a click-event and a treeLine detail card to show info and add a slider to change the treeline width~

Questions: @karpaddel, @noobla11: 

1.  can /should / must a tree line (so I am referring to the area that is not available for agriculture anymore) change its width over time?
2. Do we actually need a slider? is the width of tree-line something the user can make up, or are there like typical values or even regulations?

**Comment by noobla11** [comment]
1. No, tree line does not need to change over time
2. The user can make up the width, but the total width should not be smaller than 1 m (0.5 m each side of the tree)

There does not seem to be a regulation, it is even recommenced to do the tillage as close as possible to the trees forcing the trees to root deep instead of wide (but not closer than 0.5 m). -> https://agroforst-info.de/wp-content/uploads/2020/10/Agroforst-Systeme_Leitfaden.pdf
