### ISSUE TITLE
New data uploaded

### ISSUE THREAD

**Issue by karpaddel** [hydrocode-de/integra-frontend#142]
I just uploaded a new file in bwSync&share.

It contains all data for the reduced and "final" species: 00_Reduzierte_Arten_allData_withDummy...".
Missing data are filled with dummy data for now.
There is also new meta-columns for each variable, explaining where the data comes from/how it was calculated/whether it was dummy data. These are not of interest for the tool, but very important as an overview for us.

**Comment by mmaelicke** [comment]
This is in process.

Unfortunately, the data model changed quite substantially again and I have to fix the data usage all over the place in the application. This also made the re-processing of the shades necessary (which is still dummy data).

@karpaddel is there an update on the shade data? Now would be the right time to upload real data instead of dummy data (again).

@noobla11 I could only link icons to three species (Vogelbeere, Berg und Feldahorn). There are way more icons, but the species do not show up in the updated species list. Is this still in progress, or will we have to handle species without icons? Or did I miss something?

**Comment by mmaelicke** [comment]
OK, I close this now, as the data is uploaded / uploading.

We now have authentication and can upload **or update** tables from google colab. This will make updates way easier.
