### ISSUE TITLE
Verlust durch Baumstreifenfläche zum Beschattung hinzufügen

### ISSUE THREAD

**Issue by mmaelicke** [hydrocode-de/integra-frontend#153]
Der Flächenverlust durch Baumstreifen soll mit in den Beschattungsverlust aufgenommen werden (schatten tab)

**Comment by karpaddel** [comment]
Here is our idea of how the shade-tab should look like, for your orientation @mmaelicke @JesJehle. 

- we would like the positions to be as close as possible to this
- the text for the heading, normal text and the pop-ups can be copied as they are
- for numbers, we would like only one decimal number to keep clarity
- for colors we are currently working on a color palette for the whole app, we'll share this soon with you, but shade is probably going to stay blue

![image](https://github.com/hydrocode-de/integra-frontend/assets/153747277/adfd622d-a935-4cf4-b17f-2c7d1cc7f274)

**Comment by karpaddel** [comment]
We would opt for the conversion to m², if possible:)

**Comment by mmaelicke** [comment]
OK. Just to clarify: In our last meeting I understood you, that you want a third category in the pie chart: Verlust durch Baumstreifen, beschattete Ackerfläche und unbeschattete Ackerfläche.
Your suggestion in the image above would show only the ackerfläche, while the total area is only added as a text info. Is that on purpose? Or did I get you wrong in the meeting?

**Comment by karpaddel** [comment]
You understood correctly, only that we redecided since the last meeting. We now think that the original purpose of the tab and graph (shade) would get lost if we add a third category. Therefore we decided to have the total area and agricultural area only as text info with the pop-up explaining that the agricultural area is exclusive of tree row loss.

So, we would like it as in the image above:)
