### ISSUE TITLE
Fix the Baumartenauswahl tab

### ISSUE THREAD

**Issue by mmaelicke** [hydrocode-de/integra-frontend#204]

**Comment by noobla11** [comment]
![image](https://github.com/hydrocode-de/integra-frontend/assets/76469988/22500612-ee1f-43ab-b010-f61dc70b4694)

**Comment by noobla11** [comment]
Rote Linie soll die Angabe aus der Karte "Meine Agrarfläche" darstellen: 

![image](https://github.com/hydrocode-de/integra-frontend/assets/76469988/64a9e7e3-c18e-47f3-b7ec-b3e7336ad033)

**Comment by noobla11** [comment]
In this context the top part of the summary might to be changed as well so that the information given in "Meine Agrarfläche" ist not editable. Or do you think it would be beneficial to be able to edit it here as well? @JoshuaBWWD @mmaelicke 
Maybe something like this?:

![image](https://github.com/hydrocode-de/integra-frontend/assets/76469988/42a77d49-ac24-4aa3-a697-15ca3e5e2990)


@Mirko, if this is not the correct issue to emntion it maybe you can move it somewhere else?

**Comment by mmaelicke** [comment]
I not sure if it is necessary to rename the Title. 

One, I think, huge benefit would be with issue #176, when the user wants to load a previously saved AFS, we could use individual titles to let the user identify the correct save faster.

**Comment by noobla11** [comment]
> I not sure if it is necessary to rename the Title.
> 
> One, I think, huge benefit would be with issue #176, when the user wants to load a previously saved AFS, we could use individual titles to let the user identify the correct save faster.

Yes this was our thought with this one :)

**Comment by mmaelicke** [comment]
The component to rename can easily be re-used or moved somewhere else. So we do not need to make a decision now

**Comment by JoshuaBWWD** [comment]
> ![image](https://private-user-images.githubusercontent.com/76469988/344609896-22500612-ee1f-43ab-b010-f61dc70b4694.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4NDY1MTgsIm5iZiI6MTcxOTg0NjIxOCwicGF0aCI6Ii83NjQ2OTk4OC8zNDQ2MDk4OTYtMjI1MDA2MTItZWUxZi00M2FiLWIwMTAtZjYxZGM3MGI0Njk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDE1MDMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkOTdlOTgyZjRiZjJhMzkzZWZlY2RiZDM4YTk1ZGNhYzIzMDE0OWZlNDJmODZlYTk3OGU4NzE0YzQ5Y2M5OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bOfQeF5yDZHk5VRIq-pcKr5K5xZu4oUOOH41Kvm0Wmw)

AND maybe add a green "BESTÄTIGEN" button to close the window and proceed?!

**Comment by JoshuaBWWD** [comment]
> ![image](https://private-user-images.githubusercontent.com/76469988/344609896-22500612-ee1f-43ab-b010-f61dc70b4694.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MjE1MDUsIm5iZiI6MTcxOTkyMTIwNSwicGF0aCI6Ii83NjQ2OTk4OC8zNDQ2MDk4OTYtMjI1MDA2MTItZWUxZi00M2FiLWIwMTAtZjYxZGM3MGI0Njk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDExNTMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiMDIyYTRlZTJkNmYzZGY5MDU5MzIxYTZmOGI0ZGRjMTc5MDBmNWVjZGZiNzJmNzY3ZmVmOWJkMmJmNGNjOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3BH0BgK1t-Lu6cF7dAdZOps0cLuWLqzrAHdiRLpMkSc)

AND maybe add a green "BESTÄTIGEN" button to close the window and proceed?!

**Comment by JoshuaBWWD** [comment]
<img width="1440" alt="Bildschirmfoto 2024-07-02 um 14 27 26" src="https://github.com/hydrocode-de/integra-frontend/assets/169056528/144a58c5-c08f-457f-9bf5-f995cbead8c0">

As displayed by the screenshot, whenever I add a second tree row in the "Gehölzauswahl" tab, the tab exceed the margin and thus the "delete" button (to delete eg single trees) disappear. Is it possible to add a "scroll" function for that tab?

**Comment by JoshuaBWWD** [comment]
![grafik](https://github.com/hydrocode-de/integra-frontend/assets/169056528/6a0df2f3-feae-4654-9dad-10ab896be26d)
NOT SUPER IMPORTANT!

- maybe it´s an old issue, but for uniformity reasons, I would generally use "Artenauswahl" also in the overview, instead of "Gehölzauswahl" which after clicking on it becomes "Artenauswahl";
- also for uniformity reasons, I would display the titles and subtitles of "Standortansprüche", "Nutzungsmöglichkeiten" and "Blüten und Bienen" from the Artenauswahl-Tab, all centered, as shown by @noobla11 in the first slide of this issue. Thanks!
