### ISSUE TITLE
Create tree icons with Midjourney

### ISSUE THREAD

**Issue by JesJehle** [hydrocode-de/integra-frontend#22]
* Tree icons for different ages for specific tree species (Wildkirsche and default tree)

**Comment by mmaelicke** [comment]
We got some data, look at #23 please.

There is a lot of stuff there, couldn't find a Wildkirsche so far...

**Comment by JesJehle** [comment]
#50 I used bergahorn instead. 
We need to think about a sizing and naming system for the different images:

* Let's define age groups on a numerical scale instead of naming conventions. it's simpler to read, understand and write.
   * let's say 10 age groups 1 to age 30?
* The sizing system should be fixed and based on the actual size of the trees (more or less)
    * next (agegroup 1 -> 64*64, next (agegroup 1 -> 72*72 and so on...
 * We should implement a draft for bergahorn first and discuss this with Chris.
![image](https://github.com/hydrocode-de/integra-frontend/assets/23353378/a04a3d74-7cff-47af-8349-4233ae7158f7)

**Comment by mmaelicke** [comment]
We should discuss this in more detail
> 
> * Let's define age groups on a numerical scale instead of naming conventions. it's simpler to read, understand and write.
> 

Agree
  
>   * let's say 10 age groups 1 to age 30?

Nope. We have data from 1 to 100 years. I guess 10 groups is way too much

> * The sizing system should be fixed and based on the actual size of the trees (more or less)

That is really complicated. I think the sizing of symbols should solely depend on the zoom level, otherwise that will grow too complicated to handle. For the actual tree size I already have the PR #51 . This implements the tree sizes as exactly as it can get with respect to the data. I would rather use a to-view, repeatable image to make use of the fill-pattern then. But I honestly like the idea of separating data-rendering (canopy) from semantics (tree icon) as they serve two different purposes.
>   
>   * next (agegroup 1 -> 64_64, next (agegroup 1 -> 72_72 and so on...
> * We should implement a draft for bergahorn first and discuss this with Chris.
 
Maybe we have a call about this?
