### ISSUE TITLE
Adding Popover for setting tree properties

### ISSUE THREAD

**Issue by JesJehle** [hydrocode-de/integra-frontend#94]
On click via map.
<img width="509" alt="image" src="https://github.com/hydrocode-de/integra-frontend/assets/23353378/487572e3-e388-4ed8-8634-be824c05f075">

**Comment by mmaelicke** [comment]
maybe we also fit some basic info about the tree there, that would not be visible somewhere else. Thinking of: age, height. Could be helpful as they directly influence the shade and blühangebot

**Comment by JesJehle** [comment]
We could `merge` the `TreeLineTooltip` with the `SideTreeDetails` and make a tooltip which is opened on click rather then on hover.
The popup as displayed in above has the combined content and functionality.

**Comment by JesJehle** [comment]
I would not close this for now but still merge the draggable branch to master.

**Comment by mmaelicke** [comment]
so show up on hover or show up on click? 

I think show up on click, but at the location of the tree and then be closable by click. We just need to figure something out, how to place the popover that it does not block the screen and the tree. Especially if it gets even bigger. 
Right now, you can center the map over the tree in question, that would make no sense anymore as the tree will most likely be under the popover then.

I think that is not super high priority.

**Comment by mmaelicke** [comment]
We have three candidates for 'Blühangebot'. Nectar, Pollen and number of blossoms...

**Comment by mmaelicke** [comment]
Schatten is not yet implemented (working on the data model right now), anything else should be done with #110 

The only thing is the merge with the tooltips: The card has become so big, that it will either be off-screen, or in the middle of the screen anyway, blocking the map. Therefore I like the position better right now. 
Another approach could be to make the Card draggable, so that the user can move it somewhere.
